name: Web Build

on:
  push:
    branches:
      - master
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'

    - name: Build with Flet
      run: |
            echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}, USER: ${GITHUB_REPOSITORY%/*}, PROJECT_BASE_URL: ${GITHUB_REPOSITORY#*/}"
            flutter config --no-analytics
            flet build web --base-url ${GITHUB_REPOSITORY#*/} --route-url-strategy hash

    - name: Upload artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        name: package
        path: |
          build/
          dist/
          bin/
          lib/
          include/
          src/
        if-no-files-found: error
