name: Web Build

on:
  push:
    branches:
      - master
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      PYTHONIOENCODING: utf-8

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'

    - name: Build with Flet
      run: |
        echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY, USER: ${GITHUB_REPOSITORY%/*}, PROJECT_BASE_URL: ${GITHUB_REPOSITORY#*/}"
        flutter config --no-analytics
        flet build web --base-url "/${GITHUB_REPOSITORY#*/}" --route-url-strategy hash

    - name: Upload artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        name: package
        path: |
          build/web
          dist/
          bin/
          lib/
          include/
          src/
        if-no-files-found: error


  deploy:
    needs: build  # wait for the "build" job to get done before executing this "deploy" job

    runs-on: windows-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Deploy to GitHub Pages 🚀
        if: github.event_name == 'push'  # deploy only on push
        id: deployment
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: web-build-artifact    
